export default {
  cricket: {
    teams: [
      {
        name: "RCB",
        id: 4,
        area: "Bangalore ",
        created: {
          seconds: 1686659854,
          nanoseconds: 359000000,
        },
        isActive: true,
      },
      {
        created: {
          seconds: 1686659817,
          nanoseconds: 381000000,
        },
        isActive: true,
        id: 3,
        area: "Chennai ",
        name: "CSK",
      },
      {
        area: "Karaikadu ",
        id: 1,
        isActive: true,
        name: "KCC stars",
        created: {
          seconds: 1686656426,
          nanoseconds: 593000000,
        },
      },
      {
        area: "Karaikadu, Cuddalore",
        created: {
          seconds: 1686637722,
          nanoseconds: 770000000,
        },
        name: "KCC Killers",
        isActive: "true",
        id: 2,
      },
      {
        id: 5,
        isActive: "true",
        created: {
          seconds: 1686636906,
          nanoseconds: 67000000,
        },
        area: "Karaikadu, Cuddalore",
        name: "KCC Hunters",
      },
    ],
    matchDetails: {
      team1: {
        name: "RCB",
        id: 4,
        area: "Bangalore ",
        created: {
          seconds: 1686659854,
          nanoseconds: 359000000,
        },
        isActive: true,
      },
      team2: {
        created: {
          seconds: 1686659817,
          nanoseconds: 381000000,
        },
        isActive: true,
        id: 3,
        area: "Chennai ",
        name: "CSK",
      },
      team1Players: [
        {
          teamId: 4,
          fours: 0,
          runs: 0,
          maidens: 0,
          average: 0,
          overs: 0,
          bowlingBalls: 0,
          highestScore: 0,
          id: "64ac59c9-0a23-40c9-ba35-b6e611082ee5",
          bowlingRuns: 0,
          matches: 0,
          bestBowlingWickets: 0,
          econRate: 0,
          created: {
            seconds: 1687797398,
            nanoseconds: 396000000,
          },
          innings: 0,
          wickets: 0,
          notOuts: 0,
          sixes: 0,
          name: "Maxwell",
          strikeRate: 0,
          balls: 0,
          outs: 0,
          bestBowlingRuns: 0,
          bowlingAverage: 0,
          isActive: true,
        },
        {
          teamId: 4,
          bestBowling: 0,
          runs: 0,
          id: "33bbfc82-fcfc-4292-963b-4cea8b4dc235",
          highestScore: 0,
          isActive: true,
          fours: 0,
          matches: 0,
          sixes: 0,
          wickets: 0,
          name: "Dinesh Karthik",
          created: {
            seconds: 1686933594,
            nanoseconds: 746000000,
          },
        },
        {
          created: {
            seconds: 1686933576,
            nanoseconds: 993000000,
          },
          fours: 0,
          wickets: 0,
          highestScore: 0,
          matches: 0,
          isActive: true,
          teamId: 4,
          bestBowling: 0,
          id: "6253c6fe-c27c-4f41-86e2-f7a0b3b09b88",
          runs: 0,
          name: "Siraj",
          sixes: 0,
        },
        {
          created: {
            seconds: 1686930558,
            nanoseconds: 727000000,
          },
          isActive: true,
          teamId: 4,
          id: "80739d30-ba11-4c56-a67c-fa988b3c973f",
          name: "Kohli",
        },
      ],
      team2Players: [
        {
          bestBowlingWickets: 0,
          name: "Praba",
          highestScore: 0,
          teamId: 3,
          maidens: 0,
          sixes: 0,
          strikeRate: 0,
          outs: 0,
          isActive: true,
          created: {
            seconds: 1687629915,
            nanoseconds: 191000000,
          },
          wickets: 0,
          bowlingBalls: 0,
          runs: 0,
          bowlingRuns: 0,
          innings: 0,
          fours: 0,
          matches: 0,
          bestBowlingRuns: 0,
          overs: 0,
          balls: 0,
          bowlingAverage: 0,
          average: 0,
          notOuts: 0,
          id: "e174e2e7-acbc-4c04-8d1a-706c4c5a8be8",
        },
        {
          maidens: 0,
          strikeRate: 0,
          average: 0,
          notOuts: 0,
          bowlingBalls: 0,
          isActive: true,
          runs: 0,
          wickets: 0,
          highestScore: 0,
          teamId: 3,
          bowlingRuns: 0,
          name: "Chahar",
          overs: 0,
          sixes: 0,
          id: "21ed72bc-2fc7-4b0e-bbc7-7c8fb32d7e3b",
          outs: 0,
          bestBowlingWickets: 0,
          bestBowlingRuns: 0,
          created: {
            seconds: 1687629904,
            nanoseconds: 665000000,
          },
          bowlingAverage: 0,
          innings: 0,
          matches: 0,
          fours: 0,
          balls: 0,
        },
      ],
      overs: 10,
      toss: {
        name: "RCB",
        id: 4,
        area: "Bangalore ",
        created: {
          seconds: 1686659854,
          nanoseconds: 359000000,
        },
        isActive: true,
      },
      battingFirst: {
        name: "RCB",
        id: 4,
        area: "Bangalore ",
        created: {
          seconds: 1686659854,
          nanoseconds: 359000000,
        },
        isActive: true,
      },
      playersPerTeam: 3,
      striker: {
        teamId: 4,
        fours: 0,
        runs: 0,
        maidens: 0,
        average: 0,
        overs: 0,
        bowlingBalls: 0,
        highestScore: 0,
        id: "64ac59c9-0a23-40c9-ba35-b6e611082ee5",
        bowlingRuns: 0,
        matches: 0,
        bestBowlingWickets: 0,
        econRate: 0,
        created: {
          seconds: 1687797398,
          nanoseconds: 396000000,
        },
        innings: 0,
        wickets: 0,
        notOuts: 0,
        sixes: 0,
        name: "Maxwell",
        strikeRate: 0,
        balls: 0,
        outs: 0,
        bestBowlingRuns: 0,
        bowlingAverage: 0,
        isActive: true,
      },
      nonStriker: {
        created: {
          seconds: 1686933576,
          nanoseconds: 993000000,
        },
        fours: 0,
        wickets: 0,
        highestScore: 0,
        matches: 0,
        isActive: true,
        teamId: 4,
        bestBowling: 0,
        id: "6253c6fe-c27c-4f41-86e2-f7a0b3b09b88",
        runs: 0,
        name: "Siraj",
        sixes: 0,
      },
      openingBowler: {
        bestBowlingWickets: 0,
        name: "Praba",
        highestScore: 0,
        teamId: 3,
        maidens: 0,
        sixes: 0,
        strikeRate: 0,
        outs: 0,
        isActive: true,
        created: {
          seconds: 1687629915,
          nanoseconds: 191000000,
        },
        wickets: 0,
        bowlingBalls: 0,
        runs: 0,
        bowlingRuns: 0,
        innings: 0,
        fours: 0,
        matches: 0,
        bestBowlingRuns: 0,
        overs: 0,
        balls: 0,
        bowlingAverage: 0,
        average: 0,
        notOuts: 0,
        id: "e174e2e7-acbc-4c04-8d1a-706c4c5a8be8",
      },
      wideAllowed: true,
      noBallAllowed: true,
      byesAllowed: true,
    },
    scoreboard: {
      matchId: 0,
      isMatchCompleted: false,
      isMatchStarted: true,
      resultText: "",
      teamWon: null,
      isFirstInnings: true,
      firstInnings: {
        team: {
          name: "RCB",
          id: 4,
          area: "Bangalore ",
          created: {
            seconds: 1686659854,
            nanoseconds: 359000000,
          },
          isActive: true,
        },
        players: [
          {
            teamId: 4,
            fours: 0,
            runs: 0,
            maidens: 0,
            average: 0,
            overs: 0,
            bowlingBalls: 0,
            highestScore: 0,
            id: "64ac59c9-0a23-40c9-ba35-b6e611082ee5",
            bowlingRuns: 0,
            matches: 0,
            bestBowlingWickets: 0,
            econRate: 0,
            created: {
              seconds: 1687797398,
              nanoseconds: 396000000,
            },
            innings: 0,
            wickets: 0,
            notOuts: 0,
            sixes: 0,
            name: "Maxwell",
            strikeRate: 0,
            balls: 0,
            outs: 0,
            bestBowlingRuns: 0,
            bowlingAverage: 0,
            isActive: true,
            isOut: false,
          },
          {
            teamId: 4,
            bestBowling: 0,
            runs: 0,
            id: "33bbfc82-fcfc-4292-963b-4cea8b4dc235",
            highestScore: 0,
            isActive: true,
            fours: 0,
            matches: 0,
            sixes: 0,
            wickets: 0,
            name: "Dinesh Karthik",
            created: {
              seconds: 1686933594,
              nanoseconds: 746000000,
            },
            isOut: null,
          },
          {
            created: {
              seconds: 1686933576,
              nanoseconds: 993000000,
            },
            fours: 0,
            wickets: 0,
            highestScore: 0,
            matches: 0,
            isActive: true,
            teamId: 4,
            bestBowling: 0,
            id: "6253c6fe-c27c-4f41-86e2-f7a0b3b09b88",
            runs: 0,
            name: "Siraj",
            sixes: 0,
            isOut: false,
          },
          {
            created: {
              seconds: 1686930558,
              nanoseconds: 727000000,
            },
            isActive: true,
            teamId: 4,
            id: "80739d30-ba11-4c56-a67c-fa988b3c973f",
            name: "Kohli",
            isOut: null,
          },
        ],
        batsmen1: {
          teamId: 4,
          fours: 0,
          runs: 0,
          maidens: 0,
          average: 0,
          overs: 0,
          bowlingBalls: 0,
          highestScore: 0,
          id: "64ac59c9-0a23-40c9-ba35-b6e611082ee5",
          bowlingRuns: 0,
          matches: 0,
          bestBowlingWickets: 0,
          econRate: 0,
          created: {
            seconds: 1687797398,
            nanoseconds: 396000000,
          },
          innings: 0,
          wickets: 0,
          notOuts: 0,
          sixes: 0,
          name: "Maxwell",
          strikeRate: 0,
          balls: 0,
          outs: 0,
          bestBowlingRuns: 0,
          bowlingAverage: 0,
          isActive: true,
          isStriker: true,
        },
        batsmen2: {
          created: {
            seconds: 1686933576,
            nanoseconds: 993000000,
          },
          fours: 0,
          wickets: 0,
          highestScore: 0,
          matches: 0,
          isActive: true,
          teamId: 4,
          bestBowling: 0,
          id: "6253c6fe-c27c-4f41-86e2-f7a0b3b09b88",
          runs: 0,
          name: "Siraj",
          sixes: 0,
          isStriker: false,
        },
        currentBowler: {
          bestBowlingWickets: 0,
          name: "Praba",
          highestScore: 0,
          teamId: 3,
          maidens: 0,
          sixes: 0,
          strikeRate: 0,
          outs: 0,
          isActive: true,
          created: {
            seconds: 1687629915,
            nanoseconds: 191000000,
          },
          wickets: 0,
          bowlingBalls: 0,
          runs: 0,
          bowlingRuns: 0,
          innings: 0,
          fours: 0,
          matches: 0,
          bestBowlingRuns: 0,
          overs: 0,
          balls: 0,
          bowlingAverage: 0,
          average: 0,
          notOuts: 0,
          id: "e174e2e7-acbc-4c04-8d1a-706c4c5a8be8",
        },
        currentOver: 0,
        bowlers: [],
        balls: [],
        overs: {
          ballNum: 1,
          overNum: 0,
          overBallNum: 1,
        },
        totalRuns: 0,
        totalBalls: 0,
        wickets: 0,
        extras: 0,
      },
      secondInnings: {
        team: {
          created: {
            seconds: 1686659817,
            nanoseconds: 381000000,
          },
          isActive: true,
          id: 3,
          area: "Chennai ",
          name: "CSK",
        },
        players: [
          {
            bestBowlingWickets: 0,
            name: "Praba",
            highestScore: 0,
            teamId: 3,
            maidens: 0,
            sixes: 0,
            strikeRate: 0,
            outs: 0,
            isActive: true,
            created: {
              seconds: 1687629915,
              nanoseconds: 191000000,
            },
            wickets: 0,
            bowlingBalls: 0,
            runs: 0,
            bowlingRuns: 0,
            innings: 0,
            fours: 0,
            matches: 0,
            bestBowlingRuns: 0,
            overs: 0,
            balls: 0,
            bowlingAverage: 0,
            average: 0,
            notOuts: 0,
            id: "e174e2e7-acbc-4c04-8d1a-706c4c5a8be8",
            isOut: null,
          },
          {
            maidens: 0,
            strikeRate: 0,
            average: 0,
            notOuts: 0,
            bowlingBalls: 0,
            isActive: true,
            runs: 0,
            wickets: 0,
            highestScore: 0,
            teamId: 3,
            bowlingRuns: 0,
            name: "Chahar",
            overs: 0,
            sixes: 0,
            id: "21ed72bc-2fc7-4b0e-bbc7-7c8fb32d7e3b",
            outs: 0,
            bestBowlingWickets: 0,
            bestBowlingRuns: 0,
            created: {
              seconds: 1687629904,
              nanoseconds: 665000000,
            },
            bowlingAverage: 0,
            innings: 0,
            matches: 0,
            fours: 0,
            balls: 0,
            isOut: null,
          },
        ],
        batsmen1: null,
        batsmen2: null,
        currentBowler: null,
        currentOver: 0,
        bowlers: [],
        balls: [],
        overs: {
          ballNum: 1,
          overNum: 0,
          overBallNum: 1,
        },
        totalRuns: 0,
        totalBalls: 0,
        wickets: 0,
        extras: 0,
      },
    },
    scoreboardEntries: [
      {
        matchId: 0,
        isMatchCompleted: false,
        isMatchStarted: true,
        resultText: "",
        teamWon: null,
        isFirstInnings: true,
        firstInnings: {
          team: {
            name: "RCB",
            id: 4,
            area: "Bangalore ",
            created: {
              seconds: 1686659854,
              nanoseconds: 359000000,
            },
            isActive: true,
          },
          players: [
            {
              teamId: 4,
              fours: 0,
              runs: 0,
              maidens: 0,
              average: 0,
              overs: 0,
              bowlingBalls: 0,
              highestScore: 0,
              id: "64ac59c9-0a23-40c9-ba35-b6e611082ee5",
              bowlingRuns: 0,
              matches: 0,
              bestBowlingWickets: 0,
              econRate: 0,
              created: {
                seconds: 1687797398,
                nanoseconds: 396000000,
              },
              innings: 0,
              wickets: 0,
              notOuts: 0,
              sixes: 0,
              name: "Maxwell",
              strikeRate: 0,
              balls: 0,
              outs: 0,
              bestBowlingRuns: 0,
              bowlingAverage: 0,
              isActive: true,
              isOut: false,
            },
            {
              teamId: 4,
              bestBowling: 0,
              runs: 0,
              id: "33bbfc82-fcfc-4292-963b-4cea8b4dc235",
              highestScore: 0,
              isActive: true,
              fours: 0,
              matches: 0,
              sixes: 0,
              wickets: 0,
              name: "Dinesh Karthik",
              created: {
                seconds: 1686933594,
                nanoseconds: 746000000,
              },
              isOut: null,
            },
            {
              created: {
                seconds: 1686933576,
                nanoseconds: 993000000,
              },
              fours: 0,
              wickets: 0,
              highestScore: 0,
              matches: 0,
              isActive: true,
              teamId: 4,
              bestBowling: 0,
              id: "6253c6fe-c27c-4f41-86e2-f7a0b3b09b88",
              runs: 0,
              name: "Siraj",
              sixes: 0,
              isOut: false,
            },
            {
              created: {
                seconds: 1686930558,
                nanoseconds: 727000000,
              },
              isActive: true,
              teamId: 4,
              id: "80739d30-ba11-4c56-a67c-fa988b3c973f",
              name: "Kohli",
              isOut: null,
            },
          ],
          batsmen1: {
            teamId: 4,
            fours: 0,
            runs: 0,
            maidens: 0,
            average: 0,
            overs: 0,
            bowlingBalls: 0,
            highestScore: 0,
            id: "64ac59c9-0a23-40c9-ba35-b6e611082ee5",
            bowlingRuns: 0,
            matches: 0,
            bestBowlingWickets: 0,
            econRate: 0,
            created: {
              seconds: 1687797398,
              nanoseconds: 396000000,
            },
            innings: 0,
            wickets: 0,
            notOuts: 0,
            sixes: 0,
            name: "Maxwell",
            strikeRate: 0,
            balls: 0,
            outs: 0,
            bestBowlingRuns: 0,
            bowlingAverage: 0,
            isActive: true,
            isStriker: true,
          },
          batsmen2: {
            created: {
              seconds: 1686933576,
              nanoseconds: 993000000,
            },
            fours: 0,
            wickets: 0,
            highestScore: 0,
            matches: 0,
            isActive: true,
            teamId: 4,
            bestBowling: 0,
            id: "6253c6fe-c27c-4f41-86e2-f7a0b3b09b88",
            runs: 0,
            name: "Siraj",
            sixes: 0,
            isStriker: false,
          },
          currentBowler: {
            bestBowlingWickets: 0,
            name: "Praba",
            highestScore: 0,
            teamId: 3,
            maidens: 0,
            sixes: 0,
            strikeRate: 0,
            outs: 0,
            isActive: true,
            created: {
              seconds: 1687629915,
              nanoseconds: 191000000,
            },
            wickets: 0,
            bowlingBalls: 0,
            runs: 0,
            bowlingRuns: 0,
            innings: 0,
            fours: 0,
            matches: 0,
            bestBowlingRuns: 0,
            overs: 0,
            balls: 0,
            bowlingAverage: 0,
            average: 0,
            notOuts: 0,
            id: "e174e2e7-acbc-4c04-8d1a-706c4c5a8be8",
          },
          currentOver: 0,
          bowlers: [],
          balls: [],
          overs: {
            ballNum: 1,
            overNum: 0,
            overBallNum: 1,
          },
          totalRuns: 0,
          totalBalls: 0,
          wickets: 0,
          extras: 0,
        },
        secondInnings: {
          team: {
            created: {
              seconds: 1686659817,
              nanoseconds: 381000000,
            },
            isActive: true,
            id: 3,
            area: "Chennai ",
            name: "CSK",
          },
          players: [
            {
              bestBowlingWickets: 0,
              name: "Praba",
              highestScore: 0,
              teamId: 3,
              maidens: 0,
              sixes: 0,
              strikeRate: 0,
              outs: 0,
              isActive: true,
              created: {
                seconds: 1687629915,
                nanoseconds: 191000000,
              },
              wickets: 0,
              bowlingBalls: 0,
              runs: 0,
              bowlingRuns: 0,
              innings: 0,
              fours: 0,
              matches: 0,
              bestBowlingRuns: 0,
              overs: 0,
              balls: 0,
              bowlingAverage: 0,
              average: 0,
              notOuts: 0,
              id: "e174e2e7-acbc-4c04-8d1a-706c4c5a8be8",
              isOut: false,
            },
            {
              maidens: 0,
              strikeRate: 0,
              average: 0,
              notOuts: 0,
              bowlingBalls: 0,
              isActive: true,
              runs: 0,
              wickets: 0,
              highestScore: 0,
              teamId: 3,
              bowlingRuns: 0,
              name: "Chahar",
              overs: 0,
              sixes: 0,
              id: "21ed72bc-2fc7-4b0e-bbc7-7c8fb32d7e3b",
              outs: 0,
              bestBowlingWickets: 0,
              bestBowlingRuns: 0,
              created: {
                seconds: 1687629904,
                nanoseconds: 665000000,
              },
              bowlingAverage: 0,
              innings: 0,
              matches: 0,
              fours: 0,
              balls: 0,
              isOut: false,
            },
          ],
          batsmen1: null,
          batsmen2: null,
          currentBowler: null,
          currentOver: 0,
          bowlers: [],
          balls: [],
          overs: {
            ballNum: 1,
            overNum: 0,
            overBallNum: 1,
          },
          totalRuns: 0,
          totalBalls: 0,
          wickets: 0,
          extras: 0,
        },
      },
    ],
  },
  dashboard: false,
};
